### ISSUE TITLE
Is it possible to use Nikon wu-1a to download pictures directly to PC without the smartphone connection by directly connecting to WIFI?

### ISSUE THREAD

**Issue by jinman** [securelyfitz/Nikon#1]
I can connect to the Nikon Wu-1a WIFI from my PC, but cannot use it to download the photos wirelessly. can I use your Python scripts?

**Comment by securelyfitz** [comment]
you need a program that supports ptp-ip, like gphoto2. connect to the nikon wifi network, and then run:

> gphoto2 --port=ptpip:192.168.1.1 --get-all-files
